// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkrjsrwlcnsvsdthdngw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprcmpzcndsY25zdnNkdGhkbmd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2ODEyNDgsImV4cCI6MjA1NjI1NzI0OH0.IzkW08WQhGCD4eIEF37gRtJ9pEqUzeJpL6-uuKDor5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);